CONFIG = {
    "random_state": 42,
    "run_profile": "Balanced Demo",
    "entity_counts": {
        "customers": 6500,
        "accounts": 8000,
        "devices": 5000,
        "merchants": 1400,
        "counterparties": 4200,
        "video_sessions": 5200,
    },
    "records_per_category_min": 800,
    "records_per_category_max": 1100,
    "channels": ["UPI", "ATM", "BRANCH", "MERCHANT", "API", "DIGITAL"],
    "mule_categories": [
        "legit", "first_time_mule", "sleeper_mule", "layering_mule", "pass_through_mule",
        "fanout_mule", "cashout_mule", "merchant_mule", "synthetic_mule"
    ],
    "risky_labels": [
        "first_time_mule", "sleeper_mule", "layering_mule", "pass_through_mule",
        "fanout_mule", "cashout_mule", "merchant_mule", "synthetic_mule", "fraud_alert", "sar"
    ],
    "train_end": "2024-03-31",
    "valid_end": "2024-08-31",
    "session_gap_minutes": 180,
    "sequence_max_len": 25,
    "sequence_epochs": 3,
    "sequence_batch_size": 128,
    "enable_tensorflow_sequences": False,
    "enable_shap": False,
    "graph_sample_size": 8000,
    "ring_sample_size": 3000,
    "max_rings": 25,
    "classifier_model": "Random Forest",
    "challenger_model": "Logistic Regression",
    "classifier_estimators": 220,
    "classifier_max_depth": 12,
    "classifier_min_samples_leaf": 4,
    "calibration_method": "sigmoid",
    "alert_daily_capacity": 500,
    "review_daily_capacity": 1000,
    "demo_profiles": {
        "Executive Demo": {
            "run_profile": "Executive Demo",
            "entity_counts": {
                "customers": 3200,
                "accounts": 4100,
                "devices": 2600,
                "merchants": 800,
                "counterparties": 1800,
                "video_sessions": 2600,
            },
            "records_per_category_min": 320,
            "records_per_category_max": 460,
            "graph_sample_size": 2800,
            "ring_sample_size": 1400,
            "max_rings": 15,
            "classifier_estimators": 160,
            "classifier_max_depth": 10,
            "classifier_min_samples_leaf": 3,
        },
        "Balanced Demo": {
            "run_profile": "Balanced Demo",
            "entity_counts": {
                "customers": 6500,
                "accounts": 8000,
                "devices": 5000,
                "merchants": 1400,
                "counterparties": 4200,
                "video_sessions": 5200,
            },
            "records_per_category_min": 800,
            "records_per_category_max": 1100,
            "graph_sample_size": 8000,
            "ring_sample_size": 3000,
            "max_rings": 25,
            "classifier_estimators": 220,
            "classifier_max_depth": 12,
            "classifier_min_samples_leaf": 4,
        },
        "Boardroom Deep Dive": {
            "run_profile": "Boardroom Deep Dive",
            "entity_counts": {
                "customers": 9000,
                "accounts": 11500,
                "devices": 7600,
                "merchants": 2100,
                "counterparties": 6400,
                "video_sessions": 7600,
            },
            "records_per_category_min": 1200,
            "records_per_category_max": 1600,
            "graph_sample_size": 12000,
            "ring_sample_size": 4500,
            "max_rings": 40,
            "classifier_estimators": 260,
            "classifier_max_depth": 14,
            "classifier_min_samples_leaf": 4,
        },
    },
}
